### PR TITLE
Support the new org-mode export block syntax with retro-compatibility

### PR DESCRIPTION
**Pull request by ardumont**
Hello,

I've permitted myself to adapt your code according to what i propose and created a PR on your fork.
If you are ok with this, can you please check it's ok on your side and merge.
It will (i think) update your PR on my fork :D (interesting to see what happens here).

https://github.com/ardumont/org2jekyll/pull/32

Thanks for your help,

Cheers,

### CODE REVIEW

**Comment by ardumont** [comment]
@akopytov Did you have some time to give it any thought? 

Thanks for your reply

**Comment by akopytov** [comment]
@ardumont apologies for the delayed reply, and thanks for trying to fix my lame attempt at fixing the issue. I tried it yesterday, but ran into some issues I didn't have time to resolve.

Unfortunately, the Org developers do not bump version numbers in the 'master' branch. This is what I have in my `org-version.el` file:

``` elisp
(defun org-release ()
  "The release version of org-mode.
  Inserted by installing org-mode or when a release is made."
   (let ((org-release "8.3.4"))
     org-release))
;;;###autoload
(defun org-git-version ()
  "The Git version of org-mode.
  Inserted by installing org-mode or when a release is made."
   (let ((org-git-version "release_8.3.4-624-g2a0a37"))
     org-git-version))
```

So it reports itself as 8.3.4, which is in fact a clone of the `master` branch as of a few days ago with the new export block syntax.

I've spent some time thinking about other ways to properly detect support the new export syntax. Looking at the commit that introduced the change: http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=54318ad

It removes the org-element-block-name-alist, so perhaps we could use `(boundp org-element-block-name-alist)` as a way to decide which syntax should be used?

**Comment by ardumont** [comment]
Hello,

> apologies...

No need really ^^

> Unfortunately...
> It removes the org-element-block-name-alist, so perhaps we could use (boundp org-element-block-name-alist) as a way to decide which syntax should be used? 

That's fine by me since it seems we won't find a better solution.
Just add a `;; HACK: breaking compatibility issue with org export notation (cf. http://orgmode.org/cgit.cgi/org-mode.git/commit/?id=54318ad)` or something.

So i think, replacing `(string-lessp org-version "9.0")` with what you suggest `(boundp...)` would be the way to go.

How do we proceed, do you merge this and try and improve on this?

As a note, to test the boundp, you can use mock in tests, something like:

``` lisp
;; before breaking change
(should (string=
         "blahblah"
         (mocklet (((boundp 'boundp org-element-block-name-alist) => t))
           (org2jekyll--to-yaml-header ...)
           )))

;; after breaking change
(should (string=
         "halbhalb"
         (mocklet (((boundp 'boundp org-element-block-name-alist) => nil))
           (org2jekyll--to-yaml-header ...)
           )))
```

Cheers,

**Comment by akopytov** [comment]
Done, I hope this is what you had in mind. And yes, it works for me and passes the test suite. 

Thanks for your help and org2jekyll!

**Pull request merged**
